### ISSUE TITLE
Can't set font path

### ISSUE THREAD

**Issue by jacobq** [devotox/ember-cli-roboto-fontface#3]
This seems to hard-code the source URLs for the font files to `../../fonts/roboto/...` but that CSS is in `/assets/vendor.css` meanwhile the fonts are in `/fonts/roboto/...`. How can I override the `../../`? Could you make this work with SASS/SCSS/LESS?

**Comment by devotox** [comment]
@jacobq would you be able to make a PR to fix this?

**Comment by jacobq** [comment]
I would be willing to, but I am not sure when I will have time to try :( For now I am working around the problem by bringing in [`roboto-fontface`](https://github.com/choffmeister/roboto-fontface-bower) directly and manipulating the paths in my project's `ember-cli-build.js` file.

**Comment by devotox** [comment]
Ha so I am using the CSS version in this repo not the Sass version and i import the font files to a location and thus this should work out the box

https://github.com/devotox/ember-cli-roboto-fontface/blob/master/index.js

**Comment by jacobq** [comment]
Hmm, since you say it should work out of the box I took a second look at my situation to see why I ran into problems. It seems like it was due to how [`materialize-css`](https://github.com/Dogfalo/materialize) was coupling with Roboto. Now ([`1.0.0-beta` / since `6f3a707b`](https://github.com/Dogfalo/materialize/commit/6f3a707b922067e8826bc5024b2977ad5b8fbd58)) it seems that their styling no longer attempts to define `@font-face ...` for Roboto, and when I use `ember-cli-roboto-fontface` again it appears to work fine. I must have been doing something wrong or had those paths overridden by materialize or something. ([Dummy project here](https://github.com/jacobq/junk-app/tree/roboto-test)).

**Comment by jacobq** [comment]
Ug, I just built a simple Ember app that gets deployed on a nested URL (i.e. `ENV.rootURL = '/some/nested-path/'`) and tried to used `ember-cli-roboto-fontface` and ran into this issue again. I want it to fetch fonts from, say, `/some/nested-path/fonts/roboto/...` but the `/some/nested-path/assets/vendor.css` has `src: url(../../fonts/...` so they don't load (get 404 as the browser hits `/some/fonts/...` instead)
