### ISSUE TITLE
Where can I find breaking changes from 1.x to 2.x?

### ISSUE THREAD

**Issue by jacobq** [devotox/ember-cli-roboto-fontface#4]
Hi, I see you recently released v2.0.1 (thanks :+1:). Are there breaking changes related to this release? If so, are they documented somewhere? It [looks like](https://github.com/devotox/ember-cli-roboto-fontface/compare/v1.0.3...v2.0.1) the main thing was moving Travis from node 4.x to 6.x (node 4.x is EOL today :tada:). Do consumers of this library need to make any changes to use the new version?

**Comment by devotox** [comment]
There should be no breaking changes at all. I just updated the code to Embers new template and since its a massive change just updated as a major release just in case
